<?php

namespace Tests\Feature;

use App\Components\FeedReadComponent;
use App\Components\NoticeRefreshComponent;
use App\Components\ParseNoticeDTO;
use App\Events\NoticesParsed;
use App\Http\Controllers\RefreshNoticesCommand;
use App\Jobs\Logging;
use App\Jobs\MailSend;
use App\Listeners\LoggingNotices;
use App\Listeners\SendingToMail;
use Illuminate\Support\Facades\Event;
use Illuminate\Support\Facades\Queue;
use Tests\TestCase;

class EventNoticesTest extends TestCase
{
    private object $mock;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $arrayToEntry = [
            [
                "title" => "Радий Хабиров параолимпийцам",
                "link" => "https://www.bashinform.ru/news/1645589-vsekh/"
            ],
            [
                "title" => "ВТБ и ДОМ.РФ запускают первую",
                "link" => "https://www.bashinform.ru/news/1645581-ipoteku/"
            ]
        ];

        foreach ($arrayToEntry as $notice){
            $notices = new ParseNoticeDTO($notice['title'],$notice['link']);
        }

        $this->mock = $this->createMock(FeedReadComponent::class);
        $this->mock->expects($this->exactly(1))->method('read')->willReturn([$notices]);
    }

    public function test_intercept_event()
    {
        //arrange
        Event::fake(
            NoticesParsed::class
        );
        $refresh = new NoticeRefreshComponent();
        //act
        $instance = new RefreshNoticesCommand();
        $instance($this->mock, $refresh);
        //assert
        Event::assertDispatched(NoticesParsed::class);
    }

    public function test_checking_if_listeners()
    {
        //arrange
        Event::fake(
            NoticesParsed::class
        );
        $refresh = new NoticeRefreshComponent();
        //act
        $instance = new RefreshNoticesCommand();
        $instance($this->mock, $refresh);
        //assert
        Event::assertListening(
            NoticesParsed::class,
            LoggingNotices::class
        );
        Event::assertListening(
            NoticesParsed::class,
            SendingToMail::class
        );
    }

    public function test_sending_job_queue()
    {
        //arrange
        Queue::fake();
        $refresh = new NoticeRefreshComponent();
        //act
        $instance = new RefreshNoticesCommand();
        $instance($this->mock, $refresh);
        //assert
        Event::fake(
            NoticesParsed::class
        );
        Queue::assertPushed(Logging::class);
        Queue::assertPushed(MailSend::class);
    }
}
