<?php

namespace Tests\Feature;

use App\Components\FeedContentParser;
use App\Components\NoticeModelUpdate;
use App\Jobs\Logging;
use App\Jobs\MailSend;
use Illuminate\Support\Facades\Bus;
use Illuminate\Support\Facades\Queue;
use Tests\TestCase;

class JobsTest extends TestCase
{
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $arrayToEntry = [
            [
                "title" => "Радий Хабиров параолимпийцам",
                "link" => "https://www.bashinform.ru/news/1645589-vsekh/"
            ],
            [
                "title" => "ВТБ и ДОМ.РФ запускают первую",
                "link" => "https://www.bashinform.ru/news/1645581-ipoteku/"
            ]
        ];

        $instance = new NoticeModelUpdate();
        $mock = $this->createMock(FeedContentParser::class);
        $mock->expects($this->exactly(1))->method('getNotices')->willReturn($arrayToEntry);
        $instance($mock);
    }

    public function test_job_logging()
    {
        Queue::fake();

        $arrayToEntry =
            [
                ["title" => "Радий Хабиров параолимпийцам",
                "link" => "https://www.bashinform.ru/news/1645589-vsekh/"]
            ];
        $order = new Logging($arrayToEntry);
        $order->handle();
    }

    public function test_mail_send()
    {
        $arrayToEntry =
            [
                "title" => "Радий Хабиров параолимпийцам",
                "link" => "https://www.bashinform.ru/news/1645589-vsekh/"
            ];

        $order = new MailSend($arrayToEntry);
        $order->handle();
    }
}
